# Generated by Django 3.1.5 on 2023-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daysoff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesleaves',
            old_name='approved_by',
            new_name='handled_by',
        ),
        migrations.RemoveField(
            model_name='employeesleaves',
            name='approved',
        ),
        migrations.AddField(
            model_name='employeesleaves',
            name='approved_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
