# Generated by Django 3.1.5 on 2022-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='report_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom', 'Custom')], default='Daily', max_length=255, null=True),
        ),
    ]
