# Generated by Django 3.1.5 on 2022-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220521_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='price',
            new_name='price_column',
        ),
    ]
