# Generated by Django 3.1.5 on 2022-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220521_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='current_inventory_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='gross_sales_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='net_sales_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='previous_inventory_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='sellin_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
