# Generated by Django 3.1.5 on 2022-05-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220521_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='partner_products',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='account',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
