# Generated by Django 3.1.5 on 2022-07-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220528_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='users/avatars/default.jpg', upload_to='users/avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='users/avatars/default.jpg', upload_to='users/avatars')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='roles',
            index=models.Index(fields=['role_name'], name='users_roles_role_na_5a5749_idx'),
        ),
        migrations.AddIndex(
            model_name='roles',
            index=models.Index(fields=['id'], name='users_roles_id_9c6edd_idx'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
