# Generated by Django 3.1.5 on 2022-08-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220729_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_pet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_pet_age', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_pet_breed', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_pet_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
