FROM --platform=linux/amd64 python:3.8-bullseye

RUN mkdir /api
RUN mkdir -p /root/api/logs
RUN touch /root/api/logs/app.log.json

WORKDIR /api
ADD . /api/

ENV MODEX_URI=http://51.144.180.220
ENV MODEX_DATA_PORTS=32318
ENV MODEX_AUTH_PORTS=32118
ENV MODEX_TOKEN=auIHN6gPMptTyJAollFQjG-PnNv3EBpkTRWQZitAxCc

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DEFAULT_TIMEOUT=100
ENV DJANGO_ENV=dev
ENV PORT=5000
ENV PYTHONPATH=/usr/local/bin/pypy

RUN apt update && apt install -y build-essential libpq-dev libssl-dev python-dev
RUN apt-get install wget apt-transport-https -y

RUN pip install -r ./requirements.txt
EXPOSE ${PORT}

CMD daphne project.asgi:application -b 0.0.0.0 -p 5000
