# Generated by Django 3.1.5 on 2022-06-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VbrPartners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='vbr_partners/')),
                ('partner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_description', models.TextField(blank=True, null=True)),
                ('partner_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_administrator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'VBR Partner',
                'verbose_name_plural': 'VBR Partners',
            },
        ),
        migrations.CreateModel(
            name='VbrContracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='vbr_contracts/')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.vbrpartners')),
            ],
            options={
                'verbose_name': 'VBR Contract',
                'verbose_name_plural': 'VBR Contracts',
            },
        ),
    ]
