# Generated by Django 3.1.5 on 2022-06-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vbrcontracts',
            old_name='contract_file',
            new_name='file',
        ),
    ]
