# Generated by Django 3.1.5 on 2022-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220608_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbrcontracts',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
