# Generated by Django 3.1.5 on 2022-06-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_vbrcontracts_contract_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vbrcontracts',
            options={'ordering': ['-contract_id'], 'verbose_name': 'VBR Contract', 'verbose_name_plural': 'VBR Contracts'},
        ),
    ]
