# Generated by Django 3.1.5 on 2022-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20220610_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbrcontracts',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
