# Generated by Django 3.1.5 on 2022-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_vbrdocuments_vbrdocumenttags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vbrdocumenttags',
            name='document',
        ),
        migrations.AddField(
            model_name='vbrdocuments',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='contracts.VbrDocumentTags'),
        ),
    ]
