# Generated by Django 3.1.5 on 2023-02-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
