# Generated by Django 3.1.5 on 2023-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_auto_20230302_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_attachment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
