# Generated by Django 3.1.5 on 2023-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_documents_document_attachment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_has_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
