# Generated by Django 3.1.5 on 2023-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_documents_document_has_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_email_uploader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
