# Generated by Django 3.1.5 on 2022-08-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_file_date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_adv_file', models.FileField(blank=True, null=True, upload_to='hr/adv/')),
                ('hr_medical_leave_file', models.FileField(blank=True, null=True, upload_to='hr/medical/')),
                ('hr_warning_file', models.FileField(blank=True, null=True, upload_to='hr/warning/')),
                ('hr_adv_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Files',
                'verbose_name_plural': 'HR Files',
            },
        ),
        migrations.AddIndex(
            model_name='hrfiles',
            index=models.Index(fields=['hr_file_name'], name='humanresour_hr_file_c647a6_idx'),
        ),
        migrations.AddIndex(
            model_name='hrfiles',
            index=models.Index(fields=['id'], name='humanresour_id_e18f31_idx'),
        ),
    ]
