# Generated by Django 3.1.5 on 2022-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrFileRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_file_request_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_file_request_date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_file_type', models.CharField(blank=True, choices=[('Adv', 'Adv'), ('Medical', 'Medical Leave'), ('Warning', 'Warning')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'HR File Request',
                'verbose_name_plural': 'HR File Request',
            },
        ),
        migrations.AddIndex(
            model_name='hrfilerequest',
            index=models.Index(fields=['hr_file_request_name'], name='humanresour_hr_file_59a5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hrfilerequest',
            index=models.Index(fields=['id'], name='humanresour_id_cb200b_idx'),
        ),
    ]
