# Generated by Django 3.1.5 on 2022-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0003_hrfilerequest_hr_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfilerequest',
            name='hr_file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
