# Generated by Django 3.1.5 on 2022-08-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0004_auto_20220810_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrfiles',
            name='hr_file_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humanresources.hrfilerequest'),
        ),
    ]
