# Generated by Django 3.1.5 on 2023-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0005_hrfiles_hr_file_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentLeads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_job_description', models.TextField(blank=True, null=True)),
                ('recruitment_date_created', models.DateField(auto_now_add=True)),
                ('recruitment_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_user_age', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_user_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_user_last_company', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_user_last_education', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Recruitment',
                'verbose_name_plural': 'Recruitment',
            },
        ),
        migrations.AddIndex(
            model_name='recruitmentleads',
            index=models.Index(fields=['recruitment_name'], name='humanresour_recruit_45c7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentleads',
            index=models.Index(fields=['id'], name='humanresour_id_ee15c2_idx'),
        ),
    ]
