# Generated by Django 3.1.5 on 2023-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0006_auto_20230212_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentleads',
            name='recruitment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=255, null=True),
        ),
    ]
