# Generated by Django 3.1.5 on 2023-03-13 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auto_20220809_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollInstallments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_installment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_installment_description', models.TextField(blank=True, null=True)),
                ('payroll_installment_amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payroll_installment_amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payroll_installment_amount_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payroll_installment_amount_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payroll_installment_date', models.DateField(blank=True, null=True)),
                ('payroll_installment_file', models.FileField(blank=True, null=True, upload_to='payroll/')),
            ],
            options={
                'verbose_name': 'Payroll Installment',
                'verbose_name_plural': 'Payroll Installments',
            },
        ),
        migrations.AddField(
            model_name='payrollmanagement',
            name='payroll_date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollmanagement',
            name='payroll_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payrollinstallments',
            index=models.Index(fields=['payroll_installment_name'], name='payroll_pay_payroll_656e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollinstallments',
            index=models.Index(fields=['id'], name='payroll_pay_id_d7995a_idx'),
        ),
        migrations.AddField(
            model_name='payrollmanagement',
            name='payroll_installments',
            field=models.ManyToManyField(blank=True, null=True, to='payroll.PayrollInstallments'),
        ),
    ]
