# Generated by Django 3.1.5 on 2023-03-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20230313_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollmanagement',
            name='payroll_file',
        ),
    ]
