# Generated by Django 3.1.5 on 2023-03-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20230313_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinstallments',
            name='payroll_installment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
