# Generated by Django 3.1.5 on 2022-07-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20220729_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.managerprofile')),
                ('team_members', models.ManyToManyField(blank=True, null=True, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_description', models.TextField(blank=True, null=True)),
                ('department_logo', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('department_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.managerprofile')),
                ('department_participants', models.ManyToManyField(blank=True, null=True, related_name='departments', to='users.UserProfile')),
                ('department_teams', models.ManyToManyField(blank=True, null=True, related_name='departments', to='companymanager.Teams')),
            ],
        ),
    ]
