# Generated by Django 3.1.5 on 2023-03-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companymanager', '0003_auto_20230327_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companymanager.teammembers'),
        ),
    ]
